os:
  - linux
  - osx

notifications:
    email:
        on_success: never
        on_failure: never

language: go
go:
  - 1.7.x
  - master

script:
  - ./coverage.sh

after_success:
  - bash <(curl -s https://codecov.io/bash)

