os:
  - linux
  - osx

notifications:
    email:
        on_success: never
        on_failure: never

language: go
go:
  - 1.7.x
  - master

script:
  - go test -race -coverprofile=coverage.txt -covermode=atomic

after_success:
  - bash <(curl -s https://codecov.io/bash)
  
