version: 0.0.1.{build}

platform: x64

branches:  
  only:
    - master

clone_folder: c:\gopath\src\github.com\ismacaulay\fiz

environment:  
  GOPATH: c:\gopath

install:
  - go get -v -t ./...

build_script:  
  - go test ./...

